// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <atomic>
#include <optional>
#include "item_list.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "dh__list_string.h"

#ifdef __cplusplus
}
#endif
struct DjinniListString {
    static djinni::Handle<DjinniObjectHandle> fromCpp(const std::vector<std::string> & dc);
    static std::vector<std::string> toCpp(djinni::Handle<DjinniObjectHandle> dh);
    static djinni::Handle<DjinniOptionalObjectHandle>fromCpp(std::optional<std::vector<std::string>> dc);
    static std::optional<std::vector<std::string>> toCpp(djinni::Handle<DjinniOptionalObjectHandle> dh);
};
